R.df <- data.frame()
fix(R.df)
R.df
str(R.df)
library(reshape2)
R.df2 <- melt(R.df, id='ID')
R.df2
str(R.df2)
table(R.df2$value)
barplot(
table(
R.df2$value))
library(knitr)
library(pander)
knit('Example1.Rmd')
Pandoc.convert('Example1.md', format='docx')
pheno
pheno <- read.csv('data/pheno.csv')
pheno
head(pheno)
tail(pheno)
read.csv
?read.table
geno <- read.table('data/geno.csv', sep=',', header=T)
head(geno)
head(pheno)
?order
order(pheno$id)
o=order(pheno$id)
pheno$id[o]
o[1:10]
pheno[o,]
head(pheno[o,])
head(geno)
head(pheno)
pheno2=pheno[o,]
head(pheno2)
o[1]
View(pheno)
is.data.frame(o)
summary(pheno)
str(pheno)
s2 = as.character(sex)
s2 = as.character(pheno$sex)
str(s2)
summary(s2)
as.numeric(pheno$sex)
pheno$sex
pheno <- read.csv('data/pheno.csv', stringsAsFactors=F)
str(pheno)
pheno <- read.csv('data/pheno.csv', colClasses=c('integer','factor','integer','integer','integer','integer'))
str(pheno)
options(stringsAsFactors=F)
pheno <- read.csv('data/pheno.csv')
str(pheno)
pheno[1:20,]
as.matrix(pheno[1:20,])
is.matrix(pheno[1:20,])
is.list(pheno)
as.list(pheno[1:20,])
library(RSQLite)
sqlite <- dbDriver('SQLite')
exampledb <- dbConnect(sqlite,'data/mydb.sqlite')
dbListTables(exampledb)
sqldf('select * from phenotype limit 5', dbname='data/mydb.sqlite')
library(sqldf)
sqldf('select * from phenotype limit 5', dbname='data/mydb.sqlite')
sqldf('select * from pheno limit 5') # use the data.frame pheno
library(RSQLite)
data()
str(mtcars)
head(mtcars)
cars
head(cars)
head(mtcars)
subset(mtcars, cyl==6)
subset(mtcars, cyl==6 & mpg<20)
ifelse(mtcars$mpg<20, 'gas.guzzler','Econ')
str(mtcars)
blah <- transform(mtcars, gas = ifelse(mpg<20, 'gas.guzzler','econ'), kmpg=1.6*mpg)
str(blah)
blah <- transform(mtcars, gas = ifelse(mpg<20, 'gas.guzzler','econ'), kmpg=1.6*mpg, score=3*cyl+0.1*wt-0.01*mpg)
str(blah)
str(mtcars)
head(mtcars)
blah$mpg[3] <- NA
head(blah)
mean(blah$mpg)
mean(blah$mpg, na.rm=T)
library(plyr)
ddply(mtcars,~cyl,summarise, mean.mpg=mean(mpg, na.rm=T),median.mpg=median(mpg,na.rm=T))
subset(mtcars, cyl==4)
mean(subset(mtcars, cyl==4)$mpg)
search()
plyr::summarise
?ddply
ddply(mtcars,~cyl,summarise, mean.mpg=mean(mpg, na.rm=T),median.mpg=median(mpg,na.rm=T))
dlply(mtcars, ~cyl, .progress=T)
dlply(mtcars, ~cyl, .progress='text')
dlply(mtcars, ~cyl+gear, .progress=T)
ddply(mtcars,~cyl+gear,summarise, mean.mpg=mean(mpg, na.rm=T),median.mpg=median(mpg,na.rm=T))
plot(mpg~disp, data=mtcars)
boxplot(mpg~cyl, data=mtcars)
library(ggplot2)
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()+geom_smooth()
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()+geom_smooth()+facet_wrap(~cyl, ncol=1)
head(pheno)
pairs(pheno[, c('sbp','dbp','bmi')])
plotmatrix(pheno[, c('sbp','dbp','bmi')])
library(rCharts)
r1 <- rPlots(mpg~wt|cyl, data=mtcars)
r1 <- rPlot(mpg~wt|cyl, data=mtcars)
r1
r1 <- rPlot(mpg~wt|cyl, data=mtcars, type='point')
r1
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()+geom_smooth()+facet_wrap(~cyl, ncol=1)
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()+geom_smooth()
ggplot(mtcars, aes(x=disp, y=mpg))+geom_point()+geom_smooth()+xlab('Displacement')+ylab('Miles per gallon')+ggtitle('Workshop graph')
plot(mpg~disp, data=mtcars)
plot(mpg~disp, data=mtcars, xlab='Displacement', ylab='Miles per gallon', main='Workshop graph')
lines(lowess(mpg~disp, data=mtcars))
lines(loess(mpg~disp, data=mtcars))
plot(mpg~disp, data=mtcars, xlab='Displacement', ylab='Miles per gallon', main='Workshop graph')
lines(lowess(mtcars$disp, mtcars$mpg))
lines(lm(mpg~disp, data=mtcars))
lm(mpg~disp, data=mtcars)
summary(lm(mpg~disp, data=mtcars))
summary(lm(mpg~disp, data=mtcars))$coef
names(summary(lm(mpg~disp, data=mtcars)))
names(lm(mpg~disp, data=mtcars))
library(xtable)
install.package('xtable')
install.packages('xtable')
library(xtable)
summary(lm(mpg~disp, data=mtcars))$coef
library(knitr)
knit('Example1.Rmd')
Pandoc.convert('Example1.md', format='docx')
plot(mpg~disp, data=mtcars, xlab='Displacement',ylab='Miles per gallon')
pdf(file='graph.pdf')
plot(mpg~disp, data=mtcars, xlab='Displacement',ylab='Miles per gallon')
dev.off()
pdf(file='graph.pdf', width=5)
plot(mpg~disp, data=mtcars, xlab='Displacement',ylab='Miles per gallon')
dev.off()
savehistory("~/Downloads/workshop-master/WorkshopHistory.R")
